### ISSUE TITLE
ERROR: Could not collect unit data

### ISSUE THREAD

**Issue by SrLaguwu** [ivansaul/platzi-downloader#16]
a mi me permite usar perfectamente el script, el error que me sale solo me aparece cuando en el curso hay un quiz o algo diferente a un video, de pronto sabes como omitir estos quices y que el script continue con su trabajo?
Cuando en el curso solo hay videos, lo descarga completamente sin problemas, pero como te digo, al haber algo que no sea solo un video aparece el error, sabes como solucionarlo u omitirlo?

**Comment by ivansaul** [comment]
Hola @SrLaguwu tienes que dar mas detalles, como por ejemplo la url del curso, url de la lección,....

**Comment by Undead34** [comment]
Hola

![image](https://github.com/user-attachments/assets/c9177608-c3fc-4d8e-a935-89499b003bf9)

mismo error: https://platzi.com/cursos/figma-basico/

esa es la URL, creo que cuando llega al examen se corta.

**Comment by SrLaguwu** [comment]
mira, al momento de ingresar en el curso de ejemplo de "https://platzi.com/cursos/misterio/"  descarga sin problema hasta el video 04 , como se muestra en la imagen:
![image](https://github.com/user-attachments/assets/461061a5-6507-4f41-bcb0-55e81d7c3c7f)
luego de que termina con ese video con ese tema, sigue un quizz o unas preguntas que estan asi :
el que dice quizz 1
![image](https://github.com/user-attachments/assets/c90e9d77-9b72-4132-a6c0-dee936e77f0f)
al llegar a ese punto, es donde sale el mensaje de error de "ERROR: Could not collect unit data" solo alli.
se abre la ventana del navegador de chornium y queda el quiz, si lo cancelo sale el error, si trato de hacer el quizz demoro mucho y sale el error, si lo dejo quieto sale el error

**Comment by Undead34** [comment]
@ivansaul  escribes muy bonito Python, oye creo que de solución rápida, podemos permitir directamente las URL del video. No he trabajado con este administrador de paquetes que usas, podrías explicarme cual es el entry point de la app 🥲

**Comment by ivansaul** [comment]
Gracias por a sugerencia  @Undead34. ya lo parche #18

**Comment by Undead34** [comment]
Muchas gracias mi rey! oye no tengo mucha XP con el m3u8

estoy tratando de mejorar la calidad de video :(


![image](https://github.com/user-attachments/assets/1bc00038-0327-410f-afb6-3116d5a0fb57)


podríamos agregar eso?

**Comment by ivansaul** [comment]
> Muchas gracias mi rey! oye no tengo mucha XP con el m3u8
> 
> estoy tratando de mejorar la calidad de video :(
> 
> ![image](https://private-user-images.githubusercontent.com/90287831/387023207-1bc00038-0327-410f-afb6-3116d5a0fb57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4OTMxODAsIm5iZiI6MTczMTg5Mjg4MCwicGF0aCI6Ii85MDI4NzgzMS8zODcwMjMyMDctMWJjMDAwMzgtMDMyNy00MTBmLWFmYjYtMzExNmQ1YTBmYjU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDAxMjEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNzhlOTI1ODc0MmYwNTRmYWJlZmNkNjQ4ZWI3MmQxMzk5NDY1YjA4MWJmZWNhNTIzYjAwZTFlZmIzNTM2N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UfPHz06GBE1eRgSBgxbDFdx3C4Go8ZACVp6S_uh7CNU)
> 
> podríamos agregar eso?

@Undead34 por defecto están en 720, pero si quieres mejor calidad retorna el ultimo elemento de la lista.

`await _m3u8_dl(m3u8_urls[-1], path, **kwargs)`

https://github.com/ivansaul/platzi-downloader/blob/c696435ee0827133b421798b35739df64d4770f6/src/platzi/m3u8.py#L163

**Comment by Undead34** [comment]
Te ganaste mi follow campeón! gran proyecto hiciste me salvaste la vida, agradecido! 😊

**Comment by ivansaul** [comment]
> @ivansaul como lo solucionaste bro?
> como se pueden omitir los quices para que el plugin continue con su descarga de los videos de un curso al encontrarse algo que no sea un video?
> Estoy probándolo nuevamente después de actualizarlo con el ultimo código que actualizaste pero sigue con el mismo error en la misma situación :(

Actualizaste el script? `pip install -U platzi`

**Comment by SrLaguwu** [comment]
Si, lo actualice apenas me dijiste que cambiaste el código.
Pensé que le habías puesto algo o había que actuar de alguna manera en específico al momento de que salieran los quices cortos que hay en medio de algunos cursos.
Si depronto sabes cómo hacerlo me comentas, sino igualmente te agradezco muchísimo por hacer un script que facilite el uso y lq descarga de los cursos en cierta medida 🙏🏼

**Comment by Undead34** [comment]
> Si, lo actualice apenas me dijiste que cambiaste el código. Pensé que le habías puesto algo o había que actuar de alguna manera en específico al momento de que salieran los quices cortos que hay en medio de algunos cursos. Si depronto sabes cómo hacerlo me comentas, sino igualmente te agradezco muchísimo por hacer un script que facilite el uso y lq descarga de los cursos en cierta medida 🙏🏼

Te recomiendo que uses el código fuente directamente para garantizar que funcione de la misma forma en tu entorno. Sigue estos pasos:

1. Instala **FFmpeg** con el siguiente comando:
   
   ```bash
   winget install Gyan.FFmpeg
   ```

2. Luego, instala **pipx** usando pip y posteriormente instala **Playwright** y **Poetry** con pipx.

En el archivo `async_api.py`, específicamente en la función `download`, dentro del bucle:

```python
for jdx, unit_url in enumerate(urls, 1):
```

Envuelve todo el bloque del bucle en un `try-except`. De esta forma, el código funcionará correctamente y manejará las posibles excepciones.

**Comment by ivansaul** [comment]
> Si, lo actualice apenas me dijiste que cambiaste el código.
> Pensé que le habías puesto algo o había que actuar de alguna manera en específico al momento de que salieran los quices cortos que hay en medio de algunos cursos.
> Si depronto sabes cómo hacerlo me comentas, sino igualmente te agradezco muchísimo por hacer un script que facilite el uso y lq descarga de los cursos en cierta medida 🙏🏼

Al rato lo vuelvo a revisar, aún hay tiempo hasta media noche para aprovechar la promo.
