### ISSUE TITLE
Problema para descargar 

### ISSUE THREAD

**Issue by pattster** [ivansaul/platzi-downloader#2]
- Hola, ya había descargado unos cursos, pero ahora me arroja este problema y ya no deja descargar.

<img width="957" alt="Captura de pantalla 2023-11-19 185733" src="https://github.com/ivansaul/platzi-downloader/assets/151480065/a8b9f9f2-c7ab-414f-aeab-148c0400069d">

Me podrías ayudar x favor.

**Comment by ivansaul** [comment]
@pattster parece un error de los servidores de la plataforma, prueba borrando todos los `.part` o mejor aun borra toda la carpeta del curso y si el error persiste intenta con `python downloader.py -d yt-dlp`

**Comment by pattster** [comment]
Hola, muchas gracias, al parecer borrando la carpeta del curso y usando `python downloader.py -d yt-dlp` funcionó.
