### ISSUE TITLE
Tengo el siguiente error después de iniciar sección.

### ISSUE THREAD

**Issue by duver88** [ivansaul/platzi-downloader#3]
$ python platzi.py
Reading credentials ...
Enter the URL of the course to download: https://platzi.com/new-home/clases/2049-investigacion-mercados/32551-da-el-primer-paso-en-la-investigacion-de-mercados-/
Logging in ...

Traceback (most recent call last):
  File "C:\Users\duver\Desktop\plat\platzi-downloader\platzi.py", line 122, in <module>
    platzi.login()
  File "C:\Users\duver\Desktop\plat\platzi-downloader\platzi.py", line 39, in login
    self.driver.find_element(By.XPATH, '//input[@name="password"]').send_keys(self.password)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duver\AppData\Roaming\Python\Python312\site-packages\selenium\webdriver\remote\webdriver.py", line 742, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duver\AppData\Roaming\Python\Python312\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "C:\Users\duver\AppData\Roaming\Python\Python312\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@name="password"]"}
  (Session info: chrome=120.0.6099.217); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
        GetHandleVerifier [0x00746EE3+174339]
        (No symbol) [0x00670A51]
        (No symbol) [0x00386FF6]
        (No symbol) [0x003B9876]
        (No symbol) [0x003B9C2C]
        (No symbol) [0x003EBD42]
        (No symbol) [0x003D7054]
        (No symbol) [0x003EA104]
        (No symbol) [0x003D6DA6]
        (No symbol) [0x003B1034]
        (No symbol) [0x003B1F8D]
        GetHandleVerifier [0x007E4B1C+820540]
        sqlite3_dbdata_init [0x008A53EE+653550]
        sqlite3_dbdata_init [0x008A4E09+652041]
        sqlite3_dbdata_init [0x008997CC+605388]
        sqlite3_dbdata_init [0x008A5D9B+656027]
        (No symbol) [0x0067FE6C]
        (No symbol) [0x006783B8]
        (No symbol) [0x006784DD]
        (No symbol) [0x00665818]
        BaseThreadInitThunk [0x76787BA9+25]
        RtlInitializeExceptionChain [0x77AEBD2B+107]
        RtlClearBits [0x77AEBCAF+191]

Exception ignored in: <function Chrome.__del__ at 0x0000029523AEF1A0>
Traceback (most recent call last):
  File "C:\Users\duver\AppData\Roaming\Python\Python312\site-packages\undetected_chromedriver\__init__.py", line 843, in __del__
  File "C:\Users\duver\AppData\Roaming\Python\Python312\site-packages\undetected_chromedriver\__init__.py", line 798, in quit
OSError: [WinError 6] Controlador no v▒lido

**Comment by ivansaul** [comment]
@duver88 bueno creo ya le toca darle su mantenimiento al código. Al parecer actualizaron los elementos html. Estuve planeando reescribirlo, pero actualmente no tengo una suscripción activa en esa plataforma para poder testearlo. Vere si consigo una cuenta uno de estos dias.

**Comment by Felogomez** [comment]
podrías actualizarlo por y pasar el código por el discord?

**Comment by ivansaul** [comment]
@Felogomez  no tengo suscripción activa de platzi para testearlo. Ya lo actualizare en su momento.

**Comment by ivansaul** [comment]
@duver88 @Felogomez  ya se corrigió
